woowacourse-teams/2020-taggle

backend/admin/build.gradle, backend/build.gradle, backend/core/build.gradle, backend/web/build.gradle
* clean build 되지 않는 이슈 해결
fix #59
=> fix(backend): 프로젝트 빌드 실패현상 해결 (#59)

.gitignore
=> chore : 프로젝트 루트 경로에 gitignore 추가 (#63)

frontend/.eslintrc.js, frontend/.prettierrc.js, frontend/package-lock.json, frontend/package.json
=> chore(frontend): ESLint 및 prettier 설정 (#25)

.gitmodules, backend/web/src/main/java/com/woowacourse/taggle/WebApplication.java, backend/web/src/main/resources/application.properties, backend/web/src/test/java/com/woowacourse/taggle/WebApplicationTest.java, backend/web/src/test/java/com/woowacourse/taggle/security/config/WebSecurityConfigTest.java
=> chore(backend): oauth2 인증키 설정 submodule로 분리 (#74)

taggle-extension/.babelrc, taggle-extension/.eslintrc.js, taggle-extension/.prettierrc, taggle-extension/.prettierrc.js, taggle-extension/package-lock.json, taggle-extension/package.json, taggle-extension/src/components/TagInput.vue, taggle-extension/src/popup/popup.js, taggle-extension/webpack.config.js
=> chore(chrome-extension): eslint 및 prettier 설정 (#71)

backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
=> fix(backend): spring security 설정 일시적으로 해제 (#86)

backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java, taggle-extension/.env.dev, taggle-extension/package.json, taggle-extension/src/api/index.js
=> refactor(chrome-extension): cors header 수정 (#92)

backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java, backend/web/src/main/java/com/woowacourse/taggle/tag/controller/ApiControllerAdvice.java, backend/web/src/test/java/com/woowacourse/taggle/ControllerTest.java, backend/web/src/test/java/com/woowacourse/taggle/security/config/WebSecurityConfigTest.java
=> refactor: 태그 및 북마크 API의 예외처리를 위한 ControllerAdvice 추가 (#82)

.github/workflows/gradle.yml
=> feature(back-end): PR build 확인 github action 스크립트 (#96)

backend/web/build.gradle, backend/web/src/main/java/com/woowacourse/taggle/WebApplication.java, backend/web/src/main/resources/application.yml
=> chroe(backend): 환경에 따른 DB 설정 (#109)

.github/workflows/gradle.yml
=> chore(github action): slack 연동 제거 (#132)

backend/open-graph-api/src/main/resources/application.properties, backend/open-graph-api/src/test/java/com/woowacourse/taggle/crawler/OpenGraphCrawlerTest.java
=> fix(opengraph): 깨지는 테스트 수정 (#134)

backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Bookmark.java, backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkCreateDto.java, backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkCreateRequest.java, backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkResponse.java, backend/core/src/main/java/com/woowacourse/taggle/tag/service/BookmarkService.java, backend/core/src/test/java/com/woowacourse/taggle/tag/domain/BookmarkTest.java, backend/core/src/test/java/com/woowacourse/taggle/tag/service/BookmarkServiceTest.java, backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java, backend/web/build.gradle, backend/web/src/main/java/com/woowacourse/taggle/WebApplication.java, backend/web/src/main/java/com/woowacourse/taggle/tag/controller/BookmarkController.java, backend/web/src/main/java/com/woowacourse/taggle/tag/service/BookmarkCrawlerService.java, backend/web/src/test/java/com/woowacourse/taggle/acceptance/BookmarkAcceptanceTest.java, backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java, backend/web/src/test/java/com/woowacourse/taggle/setup/domain/BookmarkSetup.java, backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/BookmarkDocumentation.java, backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/TagDocumentation.java
=> feat(opengraph): 오픈 그래프 크롤러를 사용하여 bookmark에 값을 저장하기 (#142)

backend/web/src/frontend/vue.config.js
* 로그인 후 요청한 포트로 origin이 유지되도록 설정
=> fix(config): oauth2 로그인 요청에 대한 proxy 설정 추가 (#149)

backend/web/src/frontend/src/api/module/tag.js, backend/web/src/frontend/src/store/index.js, backend/web/src/frontend/src/store/modules/bookmarkTags.js, backend/web/src/frontend/src/store/modules/bookmarkWithTags.js, backend/web/src/frontend/src/store/modules/snackbar.js, backend/web/src/frontend/src/store/modules/tagWithBookmarks.js, backend/web/src/frontend/src/store/share/actionTypes.js, backend/web/src/frontend/src/store/share/getterTypes.js, backend/web/src/frontend/src/store/share/mutationTypes.js, backend/web/src/frontend/src/utils/constants.js, backend/web/src/frontend/src/utils/validator.js, backend/web/src/frontend/src/views/bookmark/BookmarkPage.vue, backend/web/src/frontend/src/views/bookmark/components/CardModuleItem.vue, backend/web/src/frontend/src/views/bookmark/components/CardStreamItem.vue, backend/web/src/frontend/src/views/bookmark/components/TagEditModal.vue, backend/web/src/frontend/src/views/common/component/Snackbar.vue, backend/web/src/frontend/src/views/header/component/BookmarkAddModal.vue
=> fix(frontend): 북마크 페이지 북마크 및 태그 목록 연동되지 않는 현상 해결 (#145)

backend/web/src/test/java/com/woowacourse/taggle/setup/domain/CategorySetup.java, backend/web/src/test/java/com/woowacourse/taggle/tag/controller/CategoryControllerTest.java, backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/CategoryDocumentation.java
=> fix(category): uncategorized tag의 id가 null인 경우 문서화 테스트 실패하는 문제 해결 (#119)

backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
=> fix(backend): put, delete 메소드 cors 허용 설정 변경 (#147)

backend/web/src/frontend/src/api/module/tag.js, backend/web/src/frontend/src/views/bookmark/components/BookmarkCard.vue, backend/web/src/frontend/src/views/bookmark/components/CardModule.vue, backend/web/src/frontend/src/views/bookmark/components/CardModuleItem.vue, backend/web/src/frontend/src/views/bookmark/components/CardStreamItem.vue
API URI가 변경되어 '북마크 조회' API 일부를 수정했습니다.
또한, 북마크 카드 하단 버튼이 균일한 위치에 보여지지 않은 이슈를 수정했습니다.
스크롤하면 밀려서 사라지는 '북마크 보기 방식 변경' 버튼을 고정시켰습니다.
CardModule 방식을 선택하면 카드가 한 줄에 최대 2개만 나오는 현상을 수정했습니다.
=> fix(bookmarks): 북마크 조회 페이지 수정 (#177)

backend/core/src/main/java/com/woowacourse/taggle/tag/domain/CategoryRepository.java, backend/core/src/main/java/com/woowacourse/taggle/tag/domain/TagRepository.java, backend/core/src/main/java/com/woowacourse/taggle/tag/dto/CategoryTagsResponse.java, backend/core/src/main/java/com/woowacourse/taggle/tag/service/CategoryService.java, backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java, backend/web/src/test/java/com/woowacourse/taggle/acceptance/CategoryAcceptanceTest.java
=> refactor(categories): 카테고리 순서를 보장하도록 변경 (#201)

backend/web/build.gradle, backend/web/src/docs/asciidoc/api-guide.adoc, backend/web/src/frontend/vue.config.js, backend/web/src/main/java/com/woowacourse/taggle/HomeController.java, backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
=> feat(docs): rest docs 정적 파일 생성 및 접근경로 부여 (#166)

backend/web/src/frontend/src/views/auth/LoginPage.vue
=> fix(login): 로컬 테스트 환경에서 로그인 이미지가 정상 출력되도록 수정 (#213)

backend/core/src/main/java/com/woowacourse/taggle/tag/domain/TagBookmarkRepository.java, backend/core/src/main/java/com/woowacourse/taggle/tag/service/BookmarkService.java, backend/core/src/main/java/com/woowacourse/taggle/tag/service/CategoryService.java, backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java
=> fix(tag): 태그를 항상 삭제할 수 있도록 수정 (#216)

backend/taggle-web/src/main/resources/logback/logback-access.xml, backend/taggle-web/src/main/resources/logback/logback-dev.xml, backend/taggle-web/src/main/resources/logback/logback-prod.xml
resolve #221 
resolve #222 
1. 개발운영환경 슬랙 연동
2. 개발 db localhost 변경 -> 서브 모듈
3. log 파일명 변경 -> 날짜와 서브숫자가 헷갈릴거 같아서 ()를 붙혔습니다.
=> refactor(backend): 개발 db uri 변경 및 log 리팩토링 (#221, #222)

backend/taggle-web/src/main/java/kr/taggle/WebApplication.java, backend/taggle-web/src/main/java/kr/taggle/common/config/CrawlerConfig.java, backend/taggle-web/src/main/resources/application.yml, backend/taggle-web/src/test/java/kr/taggle/security/config/WebSecurityConfigTest.java
resolve #237
생각난김에 PR 올립니다. AOP는 금요일까지 적용할게요.
=> refactor(config): springboot 설정방식 변경 (#237)

backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java, backend/taggle-web/src/test/java/kr/taggle/ControllerTest.java, backend/taggle-web/src/test/java/kr/taggle/acceptance/AcceptanceTest.java
=> refactor(backend): Spring Security 권한 재설정 (#223)

backend/taggle-core/src/main/java/kr/taggle/tag/domain/TagRepository.java, backend/taggle-core/src/main/java/kr/taggle/tag/service/TagService.java
=> fix(tag): 다른사람이 생성한 태그를 생성할 수 있도록 수정 (#251)

backend/taggle-web/src/main/resources/logback/logback.xml
=> refactor(log): 슬랙 로그 변경 및 로컬 환경에서 로그 파일 생성 제거 (#252)
